### ISSUE TITLE
[DOCS] : Custom issue templates 작성법 글 올리기

### ISSUE THREAD

**Issue by wlgudths** [wlgudths/git_practice#1]
## 어떠한 문서를 작성했나요?
- file : 01.Custom_issue_templates.md

## TODO
- [ ] Commit templates 를 준수했나요?
- [x] 문서의 목적과 내용을 명확하게 작성했나요?
- [x] 맞춤법 및 문법 오류를 확인했나요?
- [x] #2
