### ISSUE TITLE
[DOCS] : PR Templates 작성

### ISSUE THREAD

**Issue by wlgudths** [wlgudths/git_practice#3]
## 어떠한 문서를 작성했나요?
- file : 01.pr_templates.md

## TODO
- [ ] Commit templates 를 준수했나요?
- [ ] 문서의 목적과 내용을 명확하게 작성했나요?
- [ ] 맞춤법 및 문법 오류를 확인했나요?
- [ ] 관련 링크나 참고 자료를 추가했나요?
